name: sgs-qos
channels:
  - defaults
  - anaconda
dependencies:
  - jedi==0.18.0
  - prompt-toolkit==3.0.20
  - pygments==2.9.0
  - pandas==1.3.4
  - networkx==2.6.3
  - backcall==0.2.0
  - pexpect==4.8.0
  - pillow==8.3.1
  - pyparsing==2.4.7
  - ptyprocess==0.7.0
  - pytz==2021.3
  - parso==0.8.2
  - ipython==7.16.1
  - matplotlib==3.4.3
  - python-dateutil==2.8.1
  - ipython_genutils==0.2.0
  - openpyxl==3.0.9
  - numpy==1.21.5
  - python==3.7.1
  - pip==21.2.4
  - six==1.16.0
  - wcwidth==0.2.5
  - kiwisolver==1.3.2
  - et_xmlfile==1.1.0
  - traitlets==5.1.1
  - cycler==0.11.0
  - psutil==5.9.0
  - decorator==5.1.0
  - pickleshare==0.7.5
  - pip:
    - iminizinc==0.4
    - minizinc==0.4.0
    - py4j==0.10.9.5
